source "http://rubygems.org"

# Specify your gem's dependencies in k3cms_pages.gemspec
gemspec

# If you want to load a gem from a path, however, you have to do it this way:
#gem 'k3_cancan', :path => '/home/tyler/dev/framework/k3_cancan'
#gem 'devise',    :path => '/home/tyler/dev/plugins/devise'
#gem 'k3cms_trivial_authorization', :path => '/home/tyler/dev/framework/k3cms_trivial_authorization'
